apiVersion: v1
kind: Service
metadata:
  name: learn-k8s-apiserver-clusterip
spec:
  type: ClusterIP
  selector:
    app: learn-k8s-apiserver
  ports:
    - name: http
      port: 27525
      targetPort: apiport